
method:
    mcts:
        max_w: 3
        step: 5
        budget: 30
        bp_policy: "max"
        derive_policy: "modify"
    vanilla:
        budget: 30
    tot:
        max_w: 3
        step: 5
        budget: 30
        bp_policy: "max"
        derive_policy: "modify"